"use server";

import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAuthContext, assertStaff } from "@/lib/authz";
import { logAudit } from "@/lib/audit";
import { revalidatePath } from "next/cache";

const PROPERTY_IMAGES_BUCKET = "property-images";

export type BulkDeleteResult = {
  success: boolean;
  deletedCount: number;
  message?: string;
};

/**
 * Bulk delete properties - ลบหลายทรัพย์พร้อมกัน
 */
// ... imports

/**
 * Bulk delete properties - ลบหลายทรัพย์พร้อมกัน
 */
export async function bulkDeletePropertiesAction(
  ids: string[]
): Promise<BulkDeleteResult> {
  try {
    const { supabase, user, role } = await requireAuthContext();
    assertStaff(role);

    if (!ids || ids.length === 0) {
      return {
        success: false,
        deletedCount: 0,
        message: "ไม่มีรายการที่เลือก",
      };
    }

    // 0) Pre-check: Filter out properties that are SOLD or RENTED (Frontend logic)
    // or have active deals (Backend integrity)

    // A. Check Property Status
    const { data: propertiesStatus, error: propErr } = await supabase
      .from("properties")
      .select("id, status")
      .in("id", ids);

    if (propErr) throw propErr;

    // B. Check Active Deals
    const { data: activeDeals, error: checkErr } = await supabase
      .from("deals")
      .select("id, status, property_id")
      .in("property_id", ids)
      .in("status", ["SIGNED", "CLOSED_WIN"]); // Status that blocks deletion

    if (checkErr) throw checkErr;

    const blockedPropertyIds = new Set<string>();

    // Block by Property Status (matches UI)
    propertiesStatus?.forEach((p) => {
      if (p.status === "SOLD" || p.status === "RENTED") {
        blockedPropertyIds.add(p.id);
      }
    });

    // Block by Deal Status (Safety net)
    activeDeals?.forEach((d) => {
      if (d.property_id) blockedPropertyIds.add(d.property_id);
    });

    const safeIds = ids.filter((id) => !blockedPropertyIds.has(id));

    if (safeIds.length === 0) {
      return {
        success: false,
        deletedCount: 0,
        message:
          "ไม่สามารถลบรายการที่เลือกได้ เนื่องจากมีสถานะ ขายแล้ว/เช่าแล้ว ทั้งหมด",
      };
    }

    // --- Cleanup Dependencies (Using safeIds) ---

    // A) Get Deal IDs related to these properties (all statuses except the blocked ones above)
    const { data: relatedDeals } = await supabase
      .from("deals")
      .select("id")
      .in("property_id", safeIds);

    const dealIds = relatedDeals?.map((d) => d.id) || [];

    // B) Delete dependencies of Deals first
    if (dealIds.length > 0) {
      // 1. Delete Rental Contracts linked to these deals
      await supabase.from("rental_contracts").delete().in("deal_id", dealIds);

      // 2. Delete Documents linked to these Deals
      await supabase
        .from("documents")
        .delete()
        .eq("owner_type", "DEAL")
        .in("owner_id", dealIds);

      // 3. Delete Deals themselves
      await supabase.from("deals").delete().in("id", dealIds);
    }

    // C) Handle Leads linked to these properties
    await supabase
      .from("leads")
      .update({ property_id: null })
      .in("property_id", safeIds);

    // D) Handle Lead Activities linked to these properties
    await supabase
      .from("lead_activities")
      .update({ property_id: null })
      .in("property_id", safeIds);

    // E) Delete Documents linked to Property directly
    await supabase
      .from("documents")
      .delete()
      .eq("owner_type", "PROPERTY")
      .in("owner_id", safeIds);

    // F) Delete Property Features (link table)
    await supabase
      .from("property_features")
      .delete()
      .in("property_id", safeIds);

    // G) Delete Property Agents (link table)
    await supabase.from("property_agents").delete().in("property_id", safeIds);

    // H) Delete Property Matches (Generated by search)
    await supabase.from("property_matches").delete().in("property_id", safeIds);

    // I) Delete Property Image Uploads (Temp/History)
    await supabase
      .from("property_image_uploads")
      .delete()
      .in("property_id", safeIds);

    // --- Original Logic: Delete Images & Property (Using safeIds) ---

    // 1) Get all images to delete from storage
    const { data: images } = await supabase
      .from("property_images")
      .select("storage_path")
      .in("property_id", safeIds);

    // 2) Delete images from storage
    if (images && images.length > 0) {
      const pathsToRemove = images
        .map((img) => img.storage_path)
        .filter((path): path is string => !!path);

      if (pathsToRemove.length > 0) {
        // Use Admin Client to bypass RLS for storage deletion
        const adminSupabase = createAdminClient();
        await adminSupabase.storage
          .from(PROPERTY_IMAGES_BUCKET)
          .remove(pathsToRemove);
      }
    }

    // 3) Delete properties (cascade will delete property_images records if not already handled, but we handle explicit items above)
    const { error, count } = await supabase
      .from("properties")
      .delete({ count: "exact" })
      .in("id", safeIds);

    if (error) {
      console.error("Delete properties error:", error);
      throw error;
    }

    // 4) Audit log
    await logAudit(
      { supabase, user, role },
      {
        action: "property.bulk_delete",
        entity: "properties",
        entityId: safeIds.join(","),
        metadata: {
          deletedCount: count,
          skippedCount: blockedPropertyIds.size,
        },
      }
    );

    // 5) Cleanup temp uploads
    await supabase
      .from("property_image_uploads")
      .delete()
      .eq("user_id", user.id)
      .eq("status", "TEMP");

    revalidatePath("/protected/properties");

    const skippedCount = blockedPropertyIds.size;
    const msg =
      skippedCount > 0
        ? `ลบสำเร็จ ${count} รายการ (ข้าม ${skippedCount} รายการที่ขาย/เช่าแล้ว)`
        : `ลบทรัพย์สำเร็จ ${count} รายการ`;

    return {
      success: true,
      deletedCount: count ?? safeIds.length,
      message: msg,
    };
  } catch (error) {
    console.error("bulkDeletePropertiesAction error:", error);
    return {
      success: false,
      deletedCount: 0,
      message: error instanceof Error ? error.message : "เกิดข้อผิดพลาด",
    };
  }
}
