import {
  SmartMatchSettings,
  BudgetRange,
} from "@/features/smart-match/config-actions";

// Budget ranges for Rent
export const DEFAULT_RENT_RANGES: BudgetRange[] = [
  {
    id: "rent_1",
    label: "< 1.5 หมื่น",
    label_en: "< 15k",
    label_cn: "< 1.5 万",
    label_ru: "< 15к",
    min_value: 0,
    max_value: 15000,
    purpose: "RENT",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "rent_2",
    label: "1.5 - 5 หมื่น",
    label_en: "15k - 50k",
    label_cn: "1.5 - 5 万",
    label_ru: "15к - 50к",
    min_value: 15000,
    max_value: 50000,
    purpose: "RENT",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "rent_3",
    label: "5 หมื่น - 1.5 แสน",
    label_en: "50k - 150k",
    label_cn: "5 万 - 15 万",
    label_ru: "50к - 150к",
    min_value: 50000,
    max_value: 150000,
    purpose: "RENT",
    sort_order: 3,
    is_active: true,
  },
  {
    id: "rent_4",
    label: "> 1.5 แสน",
    label_en: "> 150k",
    label_cn: "> 15 万",
    label_ru: "> 150к",
    min_value: 150000,
    max_value: 999999999,
    purpose: "RENT",
    sort_order: 4,
    is_active: true,
  },
];

// Budget ranges for Buy
export const DEFAULT_BUY_RANGES: BudgetRange[] = [
  {
    id: "buy_1",
    label: "< 3 ล้าน",
    label_en: "< 3M",
    label_cn: "< 300 万",
    label_ru: "< 3М",
    min_value: 0,
    max_value: 3000000,
    purpose: "BUY",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "buy_2",
    label: "3 - 5 ล้าน",
    label_en: "3M - 5M",
    label_cn: "300 - 500 万",
    label_ru: "3М - 5М",
    min_value: 3000000,
    max_value: 5000000,
    purpose: "BUY",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "buy_3",
    label: "5 - 10 ล้าน",
    label_en: "5M - 10M",
    label_cn: "500 - 1000 万",
    label_ru: "5М - 10М",
    min_value: 5000000,
    max_value: 10000000,
    purpose: "BUY",
    sort_order: 3,
    is_active: true,
  },
  {
    id: "buy_4",
    label: "> 10 ล้าน",
    label_en: "> 10M",
    label_cn: "> 1000 万",
    label_ru: "> 10М",
    min_value: 10000000,
    max_value: 999999999,
    purpose: "BUY",
    sort_order: 4,
    is_active: true,
  },
];

export const DEFAULT_PROPERTY_TYPES = [
  {
    label: "🏠 บ้าน",
    label_en: "House",
    label_cn: "别墅/单户住宅",
    label_ru: "Дом",
    value: "HOUSE",
  },
  { label: "🏢 คอนโด", label_en: "Condo", label_cn: "公寓", label_ru: "Кондо", value: "CONDO" },
  {
    label: "🏝️ วิลล่า",
    label_en: "Villa",
    label_cn: "别墅",
    label_ru: "Вилла",
    value: "VILLA",
  },
  {
    label: "🌊 พูลวิลล่า",
    label_en: "Pool Villa",
    label_cn: "泳池别墅",
    label_ru: "Пул Вилла",
    value: "POOL_VILLA",
  },
  {
    label: "🏬 อาคารสำนักงาน / ออฟฟิศ",
    label_en: "Office",
    label_cn: "办公室",
    label_ru: "Офис",
    value: "OFFICE_BUILDING",
  },
  {
    label: "🏡 โฮมออฟฟิศ",
    label_en: "Townhome",
    label_cn: "联排别墅/店屋",
    label_ru: "Таунхаус",
    value: "TOWNHOME",
  },
  {
    label: "🌳 ที่ดิน",
    label_en: "Land",
    label_cn: "土地",
    label_ru: "Земля",
    value: "LAND",
  },
  {
    label: "🛒 โกดัง",
    label_en: "Warehouse",
    label_cn: "仓库",
    label_ru: "Склад",
    value: "WAREHOUSE",
  },
  {
    label: "🏢 อาคารพาณิชย์",
    label_en: "Commercial Bldg",
    label_cn: "商用建筑",
    label_ru: "Коммерческое здание",
    value: "COMMERCIAL_BUILDING",
  },
];

export const DEFAULT_SETTINGS: SmartMatchSettings = {
  transit_question_enabled: true,
  wizard_title: "วันนี้คุณกำลังมองหา...",
  wizard_title_en: "What are you looking for today?",
  wizard_title_cn: "您今天在寻找什么？",
  wizard_title_ru: "Что вы ищете сегодня?",
  loading_text: "กำลังวิเคราะห์ข้อมูล...",
  loading_text_en: "Analyzing data...",
  loading_text_cn: "正在分析数据...",
  loading_text_ru: "Анализ данных...",
  pdpa_text: "ข้อมูลของคุณจะถูกเก็บเป็นความลับตามนโยบาย PDPA",
  pdpa_text_en: "Your data will be kept confidential according to PDPA policy",
  pdpa_text_cn: "您的数据将根据 PDPA 政策保密",
  pdpa_text_ru: "Ваши данные будут сохранены в тайне согласно политике PDPA",
};
