import type { PropertyRow, NearbyItem, PropertyTransitInfoConsolidated, PropertyTransitV3 } from "@/features/properties/types";
import { getSafeImages, getSafeNearbyPlaces, getSafeNearbyTransits } from "@/lib/property-hardened-utils";
import { type PropertyFormValues } from "@/features/properties/schema";
import { type TransitType } from "@/features/properties/labels";

export const EMPTY_VALUES: PropertyFormValues = {
  title: "",
  title_en: "",
  title_cn: "",
  title_ru: "",
  description: "",
  description_en: "",
  description_cn: "",
  description_ru: "",
  property_type: undefined as any,
  listing_type: "SALE",
  status: "DRAFT",
  branch_id: "", 
  tenant_id: undefined,
  price: undefined,
  original_price: undefined,
  rental_price: undefined,
  original_rental_price: undefined,
  bedrooms: undefined,
  bathrooms: undefined,
  size_sqm: undefined,
  land_size_sqwah: undefined,
  floor: undefined,
  is_total_floors: false,
  min_contract_months: 12,
  verified: true,
  airbnb_daily_price: undefined,
  airbnb_monthly_price: undefined,
  airbnb_min_contract: "",
  
  maintenance_fee: undefined,
  parking_slots: undefined,
  zoning: undefined,
  ceiling_height: undefined,
  electricity_charge: "",
  water_charge: "",
  rent_free_period_days: undefined,
  office_capacity: undefined,
  maid_rooms: undefined,
  halls: undefined,
  dining_rooms: undefined,
  total_units: 1,
  sold_units: 0,
  parking_type: "COMMON",
  parking_fee_additional: undefined,
  orientation: undefined,
  price_per_sqm: undefined,
  rent_price_per_sqm: undefined,
  currency: "THB",
  
  address_line1: "",
  address_line1_en: "",
  address_line1_cn: "",
  address_line1_ru: "",
  province: "กรุงเทพมหานคร",
  district: "",
  subdistrict: "",
  postal_code: "",
  google_maps_link: "",
  popular_area: undefined,
  popular_area_en: "",
  popular_area_cn: "",
  popular_area_ru: "",
  
  owner_id: null,
  assigned_to: null,
  agent_ids: [],
  feature_ids: [],
  images: [],
  is_ai_generating: false,
  
  commission_sale_percentage: 3,
  commission_rent_months: 1,
  
  near_transit: false,
  transit_station_name: "",
  transit_station_name_en: "",
  transit_station_name_cn: "",
  transit_station_name_ru: "",
  transit_type: "BTS",
  transit_distance_meters: undefined,
  nearby_transits: [],
  nearby_places: [],
  
  is_co_agent: false,
  co_agent_name: "",
  co_agent_phone: "",
  co_agent_contact_channel: "Line",
  co_agent_contact_id: "",
  co_agent_sale_commission_percent: undefined,
  co_agent_rent_commission_months: undefined,
  
  is_pet_friendly: false,
  is_foreigner_quota: false,
  allow_smoking: false,
  allow_airbnb: false,
  is_renovated: false,
  is_fully_furnished: false,
  is_corner_unit: false,
  has_private_pool: false,
  is_selling_with_tenant: false,
  is_bare_shell: false,
  is_exclusive: false,
  
  has_garden_view: false,
  has_pool_view: false,
  has_city_view: false,
  has_unblocked_view: false,
  has_river_view: false,
  facing_east: false,
  facing_north: false,
  facing_south: false,
  facing_west: false,
  has_multi_parking: false,
  is_grade_a: false,
  is_grade_b: false,
  is_grade_c: false,
  is_column_free: false,
  is_central_air: false,
  is_split_air: false,
  has_247_access: false,
  has_fiber_optic: false,
  is_tax_registered: false,
  has_raised_floor: false,
  is_high_ceiling: false,
  is_cbd: false,
  is_smart_home: false,
  has_private_elevator: false,
  is_handicapped_friendly: false,
  is_high_floor: false,
  is_green_building: false,
  has_flexible_lease: false,
  is_fully_fitted: false,
  is_never_lived_in: false,

  // Luxury / Premium Features
  has_large_kitchen: false,
  has_western_kitchen: false,
  has_separate_thai_kitchen: false,
  has_bar_counter: false,
  has_bathtub: false,
  has_walk_in_closet: false,
  has_private_garden: false,
  has_garage: false,
  has_bbq_area: false,
  has_home_theatre: false,
  has_private_gym: false,
  has_wine_cellar: false,
  
  view_count: 0,
  trust_score: 1.0,
  has_nearby_places: false,
  requires_ai_review: false,
  property_source: "",
  video_url: "",
  floor_plan_url: "",
  version: 1,
};


export const STEP_FIELDS: Record<number, (keyof PropertyFormValues)[]> = {
  1: [
    "branch_id", "listing_type", "property_type", "province", "popular_area",
    "title", "title_en", "title_cn", "title_ru",
    "popular_area_en", "popular_area_cn", "popular_area_ru"
  ],
  2: [
    "price",
    "original_price",
    "rental_price",
    "original_rental_price",
    "price_per_sqm",
    "rent_price_per_sqm",
    "airbnb_daily_price",
    "airbnb_monthly_price",
    "airbnb_min_contract",
    "commission_sale_percentage",
    "commission_rent_months",
    // Property Details
    "bedrooms",
    "bathrooms",
    "size_sqm",
    "land_size_sqwah",
    "floor",
    "is_total_floors",
    "min_contract_months",
    "maintenance_fee",
    "parking_slots",
    "zoning",
    "ceiling_height",
    "electricity_charge",
    "water_charge",
    "rent_free_period_days",
    "parking_type",
    "parking_fee_additional",
    "orientation",
    // Stock Management
    "total_units",
    "sold_units",
    // Co-Agent Fields
    "is_co_agent",
    "co_agent_name",
    "co_agent_phone",
    "co_agent_contact_channel",
    "co_agent_contact_id",
    "co_agent_sale_commission_percent",
    "co_agent_rent_commission_months",
    "office_capacity",
    "maid_rooms",
    "halls",
    "dining_rooms",
  ],
  3: [
    "district",
    "subdistrict",
    "address_line1", "address_line1_en", "address_line1_cn", "address_line1_ru",
    "postal_code",
    "google_maps_link",
    // Transit Fields
    "near_transit",
    "transit_station_name", "transit_station_name_en", "transit_station_name_cn", "transit_station_name_ru",
    "transit_type",
    "transit_distance_meters",
    "nearby_transits",
    "nearby_places",
  ],
  4: ["images", "owner_id", "assigned_to", "agent_ids", "property_source", "video_url", "floor_plan_url"],
  5: [
    "feature_ids",
    // Boolean tags
    "verified",
    "is_pet_friendly",
    "is_foreigner_quota",
    "allow_smoking",
    "allow_airbnb",
    "is_renovated",
    "is_fully_furnished",
    "is_corner_unit",
    "has_private_pool",
    "is_selling_with_tenant",
    "is_bare_shell",
    "is_exclusive",
    "has_garden_view",
    "has_pool_view",
    "has_city_view",
    "has_unblocked_view",
    "has_river_view",
    "facing_east",
    "facing_north",
    "facing_south",
    "facing_west",
    "has_multi_parking",
    "is_grade_a",
    "is_grade_b",
    "is_grade_c",
    "is_column_free",
    "is_central_air",
    "is_split_air",
    "has_247_access",
    "has_fiber_optic",
    "is_tax_registered",
    "has_raised_floor",
    "is_high_ceiling",
    "is_cbd",
    "is_smart_home",
    "has_private_elevator",
    "is_handicapped_friendly",
    "is_high_floor",
    "is_never_lived_in",
    "is_green_building",
    "has_flexible_lease",
    "is_fully_fitted",
    // Luxury / Premium
    "has_large_kitchen",
    "has_western_kitchen",
    "has_separate_thai_kitchen",
    "has_bar_counter",
    "has_bathtub",
    "has_walk_in_closet",
    "has_private_garden",
    "has_garage",
    "has_bbq_area",
    "has_home_theatre",
    "has_private_gym",
    "has_wine_cellar",
  ],
  6: ["description", "description_en", "description_cn", "description_ru", "status"],
};

export const FIELD_LABELS: Record<string, string> = {
  // Step 1
  listing_type: "รูปแบบประกาศ",
  property_type: "ประเภททรัพย์",
  title: "ชื่อทรัพย์ (TH)",
  title_en: "Title (EN)",
  title_cn: "物业名称 (CN)",
  title_ru: "Название (RU)",
  popular_area: "ย่าน/โครงการ (TH)",
  popular_area_en: "Area (EN)",
  popular_area_cn: "区域 (CN)",
  popular_area_ru: "Район (RU)",

  // Step 2 - Price & Details
  price: "ราคาขาย",
  original_price: "ราคาตั้งขาย (เต็ม)",
  rental_price: "ค่าเช่า",
  original_rental_price: "ค่าเช่าต่อเดือน (เต็ม)",
  price_per_sqm: "ราคาขายต่อ ตร.ม.",
  rent_price_per_sqm: "ราคาเช่าต่อ ตร.ม.",
  airbnb_daily_price: "ราคาปล่อยเช่ารายวัน (Airbnb)",
  airbnb_monthly_price: "ราคาปล่อยเช่ารายเดือน (Airbnb)",
  airbnb_min_contract: "สัญญาขั้นต่ำ (Airbnb)",
  commission_sale_percentage: "% คอมมิชชั่นขาย",
  commission_rent_months: "คอมมิชชั่นเช่า (เดือน)",
  bedrooms: "ห้องนอน",
  bathrooms: "ห้องน้ำ",
  size_sqm: "พื้นที่ใช้สอย",
  land_size_sqwah: "พื้นที่ดิน",
  floor: "ชั้น",
  min_contract_months: "ขั้นต่ำสัญญา",
  maintenance_fee: "ค่าส่วนกลาง",
  parking_slots: "ที่จอดรถ",
  zoning: "โซนนิ่ง",
  ceiling_height: "ความสูงเพดาน",
  electricity_charge: "ค่าไฟ",
  water_charge: "ค่าน้ำ",
  rent_free_period_days: "ฟรีค่าเช่า",
  parking_type: "ประเภทที่จอดรถ",
  parking_fee_additional: "ค่าที่จอดรถเพิ่มเติม",
  orientation: "ทิศทาง",
  total_units: "จำนวนยูนิต",
  sold_units: "ยูนิตที่ขายแล้ว",
  office_capacity: "รองรับที่นั่งออฟฟิศ",
  maid_rooms: "ห้องแม่บ้าน",
  halls: "ห้องโถงใหญ่",
  dining_rooms: "ห้องอาหาร",

  // Co-Agent
  is_co_agent: "Co-Agent",
  co_agent_name: "ชื่อ Co-Agent",
  co_agent_phone: "เบอร์โทร Co-Agent",
  co_agent_contact_channel: "ช่องทางติดต่อ Co-Agent",
  co_agent_contact_id: "ID ติดต่อ Co-Agent",
  co_agent_sale_commission_percent: "ส่วนแบ่งขาย Co-Agent (%)",
  co_agent_rent_commission_months: "ส่วนแบ่งเช่า Co-Agent (เดือน)",

  // Step 3 - Location
  province: "จังหวัด",
  district: "อำเภอ/เขต",
  subdistrict: "ตำบล/แขวง",
  address_line1: "ที่อยู่ (TH)",
  address_line1_en: "Address (EN)",
  address_line1_cn: "地址 (CN)",
  address_line1_ru: "Адрес (RU)",
  postal_code: "รหัสไปรษณีย์",
  google_maps_link: "ลิงก์ Google Maps",
  near_transit: "ใกล้ระบบขนส่ง",
  transit_station_name: "ชื่อสถานี (TH)",
  transit_station_name_en: "Station (EN)",
  transit_station_name_cn: "车站 (CN)",
  transit_station_name_ru: "Станция (RU)",
  transit_type: "ประเภทระบบขนส่ง",
  transit_distance_meters: "ระยะทางถึงสถานี",
  nearby_places: "สถานที่ใกล้เคียง",
  nearby_transits: "การเดินทาง",

  // Step 4 - Media & Management
  images: "รูปภาพ",
  owner_id: "เจ้าของทรัพย์",
  assigned_to: "ผู้ดูแล",
  agent_ids: "เอเจนต์",
  property_source: "แหล่งที่มา",
  video_url: "ลิงก์วิดีโอ",
  floor_plan_url: "ผังอาคาร (Floor Plan)",

  // Step 5 - Features
  feature_ids: "สิ่งอำนวยความสะดวก",
  verified: "ยืนยันแล้ว",
  is_pet_friendly: "สัตว์เลี้ยงได้",
  is_foreigner_quota: "โควต้าต่างชาติ",
  allow_smoking: "สูบบุหรี่ได้",
  allow_airbnb: "รองรับ Airbnb",
  is_renovated: "ปรับปรุงใหม่",
  is_fully_furnished: "เฟอร์นิเจอร์ครบ",
  is_corner_unit: "ห้องมุม",
  has_private_pool: "สระส่วนตัว",
  is_selling_with_tenant: "ขายพร้อมผู้เช่า",
  is_bare_shell: "Bare Shell",
  is_exclusive: "Exclusive",
  is_cbd: "ย่าน CBD",
  is_smart_home: "Smart Home",
  has_private_elevator: "ลิฟต์ส่วนตัว",
  is_handicapped_friendly: "รองรับผู้พิการ",
  is_high_floor: "ชั้นสูง (High Floor)",
  is_never_lived_in: "ไม่เคยเข้าอยู่",
  is_green_building: "อาคารสีเขียว (Green Building)",
  has_flexible_lease: "สัญญาเช่ายืดหยุ่น",
  is_fully_fitted: "กั้นห้องแล้ว (Fully Fitted)",
  has_large_kitchen: "ห้องครัวใหญ่",
  has_western_kitchen: "ครัวฝรั่ง",
  has_separate_thai_kitchen: "ครัวไทยแยกส่วน",
  has_bar_counter: "เคาท์เตอร์บาร์",
  has_bathtub: "อ่างแช่ตัว",
  has_walk_in_closet: "Walk-in Closet",
  has_private_garden: "สวนส่วนตัว",
  has_garage: "โรงจอดรถ (Garage)",
  has_bbq_area: "พื้นที่ BBQ",
  has_home_theatre: "Home Theatre",
  has_private_gym: "Gym ส่วนตัว",
  has_wine_cellar: "Wine Cellar",

  // Step 6 - Review
  description: "คำอธิบาย (TH)",
  description_en: "Description (EN)",
  description_cn: "说明 (CN)",
  description_ru: "Описание (RU)",
  status: "สถานะ",
};

// Helper: Convert DB row to form values (V3 Smart Version)
export function mapRowToFormValues(
  row: Record<string, any>, 
): PropertyFormValues {
  // Extract JSONB blocks with fallback to empty objects
  const amenities = (row.amenities || {}) as Record<string, any>;
  const meta = (row.meta_data || {}) as Record<string, any>;
  const pricing = (row.pricing_details || {}) as Record<string, any>;
  const address = (row.address_info || {}) as Record<string, any>;
  const transitRaw = row.transit_info || [];
  const transit = Array.isArray(transitRaw)
    ? (transitRaw as PropertyTransitV3[])
    : ((transitRaw as unknown as PropertyTransitInfoConsolidated)?.transits || []);
  const places = Array.isArray(transitRaw)
    ? ((row.nearby_places || []) as NearbyItem[])
    : (((transitRaw as unknown as PropertyTransitInfoConsolidated)?.places || row.nearby_places || []) as NearbyItem[]);

  // 🧠 Smart Lookup Helper: Try core column first, then JSONB blocks
  const get = <T>(key: string, defaultValue: T): T => {
    const value = row[key] ?? amenities[key] ?? meta[key] ?? pricing[key] ?? address[key];
    return (value !== null && value !== undefined) ? (value as T) : defaultValue;
  };

  return {
    // 1. Core Identification
    title: get("title", ""),
    title_en: get("title_en", ""),
    title_cn: get("title_cn", ""),
    title_ru: get("title_ru", ""),
    description: get("description", ""),
    description_en: get("description_en", ""),
    description_cn: get("description_cn", ""),
    description_ru: get("description_ru", ""),
    
    // 2. Core Specs (Hot Table)
    property_type: (row.property_type as any) || "HOUSE",
    listing_type: (row.listing_type as any) || "SALE",
    status: (row.status as any) || "DRAFT",
    branch_id: String(row.branch_id || ""),
    tenant_id: (row.tenant_id as any),
    
    price: Number(row.price || pricing.price || 0) || undefined,
    original_price: Number(get("original_price", 0)) || undefined,
    rental_price: Number(row.rental_price || pricing.rental_price || 0) || undefined,
    original_rental_price: Number(get("original_rental_price", 0)) || undefined,
    
    price_per_sqm: Number(get("price_per_sqm", 0)) || 
      (row.price && row.size_sqm ? Math.round(Number(row.price) / Number(row.size_sqm)) : undefined),
    rent_price_per_sqm: Number(get("rent_price_per_sqm", 0)) ||
      (row.rental_price && row.size_sqm ? Math.round(Number(row.rental_price) / Number(row.size_sqm)) : undefined),
    airbnb_daily_price: Number(get("airbnb_daily_price", 0)) || undefined,
    airbnb_monthly_price: Number(get("airbnb_monthly_price", 0)) || undefined,
    airbnb_min_contract: get("airbnb_min_contract", ""),
    
    bedrooms: Number(row.bedrooms || 0) || undefined,
    bathrooms: Number(row.bathrooms || 0) || undefined,
    size_sqm: Number(row.size_sqm || 0) || undefined,
    land_size_sqwah: Number(row.land_size_sqwah || 0) || undefined,
    floor: Number(get("floor", 0)) || undefined,
    is_total_floors: Boolean(get("is_total_floors", false)),
    
    // 3. Details (Warm Blocks)
    min_contract_months: Number(get("min_contract_months", 12)),
    maintenance_fee: Number(get("maintenance_fee", 0)) || undefined,
    parking_slots: Number(get("parking_slots", 0)) || undefined,
    zoning: get("zoning", undefined),
    ceiling_height: Number(get("ceiling_height", 0)) || undefined,
    electricity_charge: get("electricity_charge", ""),
    water_charge: get("water_charge", ""),
    rent_free_period_days: Number(get("rent_free_period_days", 0)) || undefined,
    parking_type: get("parking_type", "COMMON"),
    parking_fee_additional: Number(get("parking_fee_additional", 0)) || undefined,
    orientation: get("orientation", undefined),
    is_bare_shell: Boolean(get("is_bare_shell", false)),
    is_exclusive: Boolean(get("is_exclusive", false)),
    has_raised_floor: Boolean(get("has_raised_floor", false)),
    currency: String(row.currency || "THB"),
    
    // 4. Address (Warm Block)
    address_line1: get("address_line1", ""),
    address_line1_en: get("address_line1_en", ""),
    address_line1_cn: get("address_line1_cn", ""),
    address_line1_ru: get("address_line1_ru", ""),
    province: get("province", ""),
    district: get("district", ""),
    subdistrict: get("subdistrict", ""),
    postal_code: get("postal_code", ""),
    google_maps_link: get("google_maps_link", ""),
    
    // 5. Management & Meta
    popular_area: get("popular_area", ""),
    popular_area_en: get("popular_area_en", ""),
    popular_area_cn: get("popular_area_cn", ""),
    popular_area_ru: get("popular_area_ru", ""),
    owner_id: (row.owner_id as any),
    property_source: get("property_source", ""),
    assigned_to: (row.assigned_to as any),
    agent_ids: (meta.agent_ids as string[]) || (row.property_agents as any[])?.map((a: any) => a.agent_id) || [],
    feature_ids: (row.property_features as any[])?.map((f: any) => f.feature_id) || [],
    
    // Media handled separately but providing fallback
    images: getSafeImages(row.images || []).map((img) => img.storage_path || img.url),
    
    commission_sale_percentage: Number(get("commission_sale_percentage", 3)),
    commission_rent_months: Number(get("commission_rent_months", 1)),
    
    // Transit
    near_transit: Boolean(get("near_transit", false)),
    transit_station_name: get("transit_station_name", ""),
    transit_station_name_en: get("transit_station_name_en", ""),
    transit_station_name_cn: get("transit_station_name_cn", ""),
    transit_station_name_ru: get("transit_station_name_ru", ""),
    transit_type: get<TransitType>("transit_type", "BTS"),
    transit_distance_meters: Number(get("transit_distance_meters", 0)) || undefined,
    nearby_transits: transit.map(t => ({
      type: (t.type || "OTHER") as TransitType,
      station_name: t.station_name || "",
      distance_meters: t.distance_meters,
      time: t.time,
      station_name_en: t.station_name_en,
      station_name_cn: t.station_name_cn,
      station_name_ru: t.station_name_ru,
    })),
    nearby_places: getSafeNearbyPlaces(places),
    
    // Co-Agent (Nested in meta)
    is_co_agent: Boolean(get("is_co_agent", false)),
    co_agent_name: get("co_agent_name", ""),
    co_agent_phone: get("co_agent_phone", ""),
    co_agent_contact_channel: get("co_agent_contact_channel", "Line"),
    co_agent_contact_id: get("co_agent_contact_id", ""),
    co_agent_sale_commission_percent: Number(get("co_agent_sale_commission_percent", 0)) || undefined,
    co_agent_rent_commission_months: Number(get("co_agent_rent_commission_months", 0)) || undefined,

    // 6. Tags & Boolean Flags
    verified: Boolean(get("verified", false)),
    is_pet_friendly: Boolean(get("is_pet_friendly", false)),
    is_foreigner_quota: Boolean(get("is_foreigner_quota", false)),
    allow_smoking: Boolean(get("allow_smoking", false)),
    allow_airbnb: Boolean(get("allow_airbnb", false)),
    is_renovated: Boolean(get("is_renovated", false)),
    is_fully_furnished: Boolean(get("is_fully_furnished", false)),
    is_corner_unit: Boolean(get("is_corner_unit", false)),
    has_private_pool: Boolean(get("has_private_pool", false)),
    is_selling_with_tenant: Boolean(get("is_selling_with_tenant", false)),
    has_garden_view: Boolean(get("has_garden_view", false)),
    has_pool_view: Boolean(get("has_pool_view", false)),
    has_city_view: Boolean(get("has_city_view", false)),
    has_unblocked_view: Boolean(get("has_unblocked_view", false)),
    has_river_view: Boolean(get("has_river_view", false)),
    facing_east: Boolean(get("facing_east", false)),
    facing_north: Boolean(get("facing_north", false)),
    facing_south: Boolean(get("facing_south", false)),
    facing_west: Boolean(get("facing_west", false)),
    has_multi_parking: Boolean(get("has_multi_parking", false)),
    is_grade_a: Boolean(get("is_grade_a", false)),
    is_grade_b: Boolean(get("is_grade_b", false)),
    is_grade_c: Boolean(get("is_grade_c", false)),
    is_column_free: Boolean(get("is_column_free", false)),
    is_central_air: Boolean(get("is_central_air", false)),
    is_split_air: Boolean(get("is_split_air", false)),
    has_247_access: Boolean(get("has_247_access", false)),
    has_fiber_optic: Boolean(get("has_fiber_optic", false)),
    is_tax_registered: Boolean(get("is_tax_registered", false)),
    is_high_ceiling: Boolean(get("is_high_ceiling", false)),
    is_cbd: Boolean(get("is_cbd", false)),
    is_smart_home: Boolean(get("is_smart_home", false)),
    has_private_elevator: Boolean(get("has_private_elevator", false)),
    is_handicapped_friendly: Boolean(get("is_handicapped_friendly", false)),
    is_high_floor: Boolean(get("is_high_floor", false)),
    is_never_lived_in: Boolean(get("is_never_lived_in", false)),
    is_green_building: Boolean(get("is_green_building", false)),
    has_flexible_lease: Boolean(get("has_flexible_lease", false)),
    is_fully_fitted: Boolean(get("is_fully_fitted", false)),
    has_large_kitchen: Boolean(get("has_large_kitchen", false)),
    has_western_kitchen: Boolean(get("has_western_kitchen", false)),
    has_separate_thai_kitchen: Boolean(get("has_separate_thai_kitchen", false)),
    has_bar_counter: Boolean(get("has_bar_counter", false)),
    has_bathtub: Boolean(get("has_bathtub", false)),
    has_walk_in_closet: Boolean(get("has_walk_in_closet", false)),
    has_private_garden: Boolean(get("has_private_garden", false)),
    has_garage: Boolean(get("has_garage", false)),
    has_bbq_area: Boolean(get("has_bbq_area", false)),
    has_home_theatre: Boolean(get("has_home_theatre", false)),
    has_private_gym: Boolean(get("has_private_gym", false)),
    has_wine_cellar: Boolean(get("has_wine_cellar", false)),
    
    floor_plan_url: String(get("floor_plan_url", "")),
    video_url: String(get("video_url", "")),
    office_capacity: get("office_capacity", "") ? String(get("office_capacity", "")) : "",
    maid_rooms: Number(get("maid_rooms", 0)) || undefined,
    halls: Number(get("halls", 0)) || undefined,
    dining_rooms: Number(get("dining_rooms", 0)) || undefined,
    
    // Extra Info
    view_count: Number(row.view_count || meta.view_count || 0),
    trust_score: Number(row.trust_score || meta.trust_score || 1.0),
    has_nearby_places: Boolean(row.has_nearby_places || meta.has_nearby_places || false),
    requires_ai_review: Boolean(row.requires_ai_review || meta.requires_ai_review || false),
    
    // Stock Management
    total_units: Number(get("total_units", 1)),
    sold_units: Number(get("sold_units", 0)),

    // Versioning
    version: Number(row.version || meta.version || 1),
  };
}
