import { type PropertyFormValues } from "@/features/properties/schema";
import type { PropertyRow } from "@/features/properties/types";

export const EMPTY_VALUES: PropertyFormValues = {
  title: "",
  description: "",
  property_type: undefined as any,
  listing_type: undefined as any,
  status: "DRAFT",
  price: undefined,
  original_price: undefined,
  rental_price: undefined,
  original_rental_price: undefined,
  bedrooms: undefined,
  bathrooms: undefined,
  size_sqm: undefined,
  land_size_sqwah: undefined,
  floor: undefined,
  min_contract_months: 12, // Default to 1 year
  verified: false,

  maintenance_fee: undefined,
  parking_slots: undefined,
  zoning: undefined,
  ceiling_height: undefined,
  electricity_charge: "",
  water_charge: "",
  rent_free_period_days: undefined,
  parking_type: "COMMON",
  parking_fee_additional: undefined,
  orientation: undefined,
  is_bare_shell: false,
  is_exclusive: false,
  has_raised_floor: false,
  currency: "THB",
  property_source: "",
  owner_id: null,
  assigned_to: null,
  agent_ids: [],
  images: [],
  commission_sale_percentage: 3,
  commission_rent_months: 1,
  popular_area: undefined,
  near_transit: false,
  transit_station_name: "",
  transit_type: "BTS",
  transit_distance_meters: undefined,
  is_co_agent: false,
  co_agent_name: "",
  co_agent_phone: "",
  co_agent_contact_channel: "Line",
  co_agent_contact_id: "",
  co_agent_sale_commission_percent: undefined,
  co_agent_rent_commission_months: undefined,
  is_pet_friendly: false,
  is_foreigner_quota: false, // Default
  allow_smoking: false, // Default
  is_renovated: false,
  // is_unfurnished removed
  is_fully_furnished: false,
  is_corner_unit: false,
  has_private_pool: false,
  is_selling_with_tenant: false,
  has_garden_view: false,
  has_pool_view: false,
  has_city_view: false,
  facing_east: false,
  facing_north: false,
  has_multi_parking: false,
  is_grade_a: false,
  is_grade_b: false,
  is_grade_c: false,
  is_column_free: false,
  is_central_air: false,
  is_split_air: false,
  has_247_access: false,
  has_fiber_optic: false,
  is_tax_registered: false,
  feature_ids: [],
  nearby_places: [],
  nearby_transits: [],
};

export const STEP_FIELDS: Record<number, (keyof PropertyFormValues)[]> = {
  1: ["listing_type", "property_type", "title", "popular_area"],
  2: [
    "price",
    "original_price",
    "rental_price",
    "original_rental_price",
    "commission_sale_percentage",
    "commission_rent_months",
    // Co-Agent Fields
    "co_agent_name",
    "co_agent_phone",
    "co_agent_contact_channel",
    "co_agent_contact_id",
    "co_agent_sale_commission_percent",
    "co_agent_rent_commission_months",
  ],
  3: [
    "province",
    "district",
    "subdistrict",
    "address_line1",
    "postal_code",
    "google_maps_link",
    // Transit Fields
    "near_transit",
    "transit_station_name",
    "transit_type",
    "transit_distance_meters",
    "nearby_transits",
  ],
  4: ["images", "owner_id"],
  5: ["feature_ids"],
  6: ["description"],
};

export const FIELD_LABELS: Record<keyof PropertyFormValues | string, string> = {
  listing_type: "รูปแบบประกาศ",
  property_type: "ประเภททรัพย์",
  title: "ชื่อทรัพย์",
  price: "ราคาขาย",
  original_price: "ราคาตั้งขาย (เต็ม)",
  rental_price: "ค่าเช่า",
  original_rental_price: "ค่าเช่าต่อเดือน (เต็ม)",
  commission_sale_percentage: "% คอมมิชชั่นขาย",
  commission_rent_months: "คอมมิชชั่นเช่า (เดือน)",
  province: "จังหวัด",
  district: "อำเภอ/เขต",
  subdistrict: "ตำบล/แขวง",
};

// Helper: Convert DB row to form values
export function mapRowToFormValues(
  row: PropertyRow,
  images?: string[],
): PropertyFormValues {
  const structuredData = row.structured_data as unknown as {
    is_co_agent?: boolean;
    co_agent_name?: string;
    co_agent_phone?: string;
    co_agent_contact_channel?: "LINE" | "FB" | "TEL";
    co_agent_contact_id?: string;
    co_agent_sale_commission_percent?: number;
    co_agent_rent_commission_months?: number;
  } | null;

  return {
    title: row.title ?? "",
    description: row.description ?? undefined,
    property_type: row.property_type ?? "HOUSE",
    listing_type: row.listing_type ?? "SALE",
    status: row.status ?? "DRAFT",
    price: row.price ?? undefined,
    original_price: row.original_price ?? undefined,
    rental_price: row.rental_price ?? undefined,
    original_rental_price: row.original_rental_price ?? undefined,
    bedrooms: row.bedrooms ?? undefined,
    bathrooms: row.bathrooms ?? undefined,
    size_sqm: row.size_sqm ?? undefined,
    land_size_sqwah: row.land_size_sqwah ?? undefined,
    floor: row.floor ?? undefined,
    min_contract_months: row.min_contract_months ?? undefined,
    maintenance_fee: row.maintenance_fee ?? undefined,
    parking_slots: row.parking_slots ?? undefined,
    zoning: row.zoning ?? undefined,
    currency: row.currency ?? "THB",
    address_line1: row.address_line1 ?? "",
    province: row.province ?? "",
    district: row.district ?? "",
    subdistrict: row.subdistrict ?? "",
    postal_code: row.postal_code ?? "",
    google_maps_link: row.google_maps_link ?? undefined,
    popular_area: row.popular_area ?? undefined,
    owner_id: row.owner_id ?? undefined,
    property_source: row.property_source ?? undefined,
    assigned_to: row.assigned_to ?? undefined,
    agent_ids: [],
    images: images ?? [],
    commission_sale_percentage: row.commission_sale_percentage ?? 3,
    commission_rent_months: row.commission_rent_months ?? 1,
    near_transit: row.near_transit ?? false,
    transit_station_name: row.transit_station_name ?? "",
    transit_type: (row.transit_type as any) ?? "BTS",
    transit_distance_meters: row.transit_distance_meters ?? undefined,
    is_co_agent: structuredData?.is_co_agent || false,
    co_agent_name: structuredData?.co_agent_name || "",
    co_agent_phone: structuredData?.co_agent_phone || "",
    co_agent_contact_channel:
      structuredData?.co_agent_contact_channel || "LINE",
    co_agent_contact_id: structuredData?.co_agent_contact_id || "",
    co_agent_sale_commission_percent:
      structuredData?.co_agent_sale_commission_percent || undefined,
    co_agent_rent_commission_months:
      structuredData?.co_agent_rent_commission_months || undefined,

    // Tags
    verified: row.verified ?? false,
    is_pet_friendly: (row.meta_keywords || []).includes("Pet Friendly"),
    is_foreigner_quota: (row.meta_keywords || []).includes(
      "Foreigner Friendly",
    ),
    allow_smoking: (row.meta_keywords || []).includes("Smoking Allowed"),
    is_renovated: (row.meta_keywords || []).includes("Renovated"),
    // is_unfurnished removed
    is_fully_furnished: (row.meta_keywords || []).includes("Fully Furnished"),
    is_corner_unit: (row.meta_keywords || []).includes("Corner Unit"),
    has_private_pool: (row.meta_keywords || []).includes("Private Pool"),
    is_selling_with_tenant: (row.meta_keywords || []).includes(
      "Selling with Tenant",
    ),
    has_garden_view: (row.meta_keywords || []).includes("Garden View"),
    has_pool_view: (row.meta_keywords || []).includes("Pool View"),
    has_city_view: (row.meta_keywords || []).includes("City View"),
    facing_east: (row.meta_keywords || []).includes("East Facing"),
    facing_north: (row.meta_keywords || []).includes("North Facing"),
    has_multi_parking: (row.meta_keywords || []).includes("Multi-Parking"),
    is_grade_a: (row.meta_keywords || []).includes("Grade A Building"),
    is_grade_b: (row.meta_keywords || []).includes("Grade B Building"),
    is_grade_c: (row.meta_keywords || []).includes("Grade C Building"),
    is_column_free: (row.meta_keywords || []).includes("Column-Free"),
    is_central_air: (row.meta_keywords || []).includes("Central Air-con"),
    is_split_air: (row.meta_keywords || []).includes("Split Air-con"),
    has_247_access: (row.meta_keywords || []).includes("24/7 Access"),
    has_fiber_optic: (row.meta_keywords || []).includes(
      "High-Speed Fiber Optic",
    ),
    is_tax_registered: (row.meta_keywords || []).includes("Tax Registered"),
    feature_ids: [],
    nearby_places: (row.nearby_places as any[]) || [],
    nearby_transits: ((row as any).nearby_transits as any[]) || [],
    ceiling_height: row.ceiling_height ?? undefined,
    electricity_charge: row.electricity_charge ?? "",
    water_charge: row.water_charge ?? "",
    rent_free_period_days: row.rent_free_period_days ?? undefined,
    parking_type: (row.parking_type as any) ?? "COMMON",
    parking_fee_additional: row.parking_fee_additional ?? undefined,
    orientation: (row.orientation as any) ?? undefined,
    is_bare_shell: row.is_bare_shell ?? false,
    is_exclusive: row.is_exclusive ?? false,
    has_raised_floor: row.has_raised_floor ?? false,
  };
}
