import {
  Check,
  Waves,
  Dumbbell,
  ShieldCheck,
  Camera,
  TreeDeciduous,
  Car,
  Briefcase,
  Sofa,
  Wifi,
  Fan,
  Box,
  Utensils,
  Tv,
  Thermometer,
  Zap,
  Coffee,
  ShoppingBag,
  Bus,
  Train,
  School,
  Hospital,
  Sun,
  Moon,
  Wind,
  Droplets,
  UserCheck,
  User,
  Users,
  Cpu,
  Layout,
  Microscope,
  CarFront,
  Plane,
} from "lucide-react";

export const ICON_MAP: Record<string, any> = {
  check: Check,
  waves: Waves,
  dumbbell: Dumbbell,
  "shield-check": ShieldCheck,
  camera: Camera,
  "tree-deciduous": TreeDeciduous,
  car: Car,
  "car-front": CarFront,
  briefcase: Briefcase,
  sofa: Sofa,
  wifi: Wifi,
  fan: Fan,
  utensils: Utensils,
  tv: Tv,
  thermometer: Thermometer,
  zap: Zap,
  coffee: Coffee,
  shopping: ShoppingBag,
  bus: Bus,
  train: Train,
  school: School,
  hospital: Hospital,
  airport: Plane,
  plane: Plane,
  sun: Sun,
  moon: Moon,
  wind: Wind,
  water: Droplets,
  droplets: Droplets,
  box: Box,
  "user-check": UserCheck,
  user: User,
  users: Users,
  cpu: Cpu,
  layout: Layout,
  microscope: Microscope,
};

export const DEFAULT_ICON = Box;
