-- Migration: Add Luxury / Premium Feature Flags (Deprecated/No-op in V3)
--
-- In V3, the legacy flat table `properties` has been replaced by a VIEW.
-- All amenities and premium feature flags (e.g. has_large_kitchen, has_bathtub, etc.)
-- are stored dynamically inside the JSONB column `properties_details.amenities`.
--
-- Therefore, adding flat columns to the `properties` relation is no longer needed
-- and would fail since `properties` is a VIEW.
-- This file is kept as a no-op placeholder to avoid migration history mismatch.
