-- Seed comprehensive Bangkok transit stations into ref_master_data
-- Supports BTS (Sukhumvit/Silom), MRT (Blue/Purple/Yellow/Pink), ARL, Gold, SRT Red, and BRT

INSERT INTO public.ref_master_data (type, code, label, is_active, sort_order, metadata) VALUES
-- ==========================================
-- 🟢 BTS Sukhumvit Line (ครบทุกสถานี คูคต - เคหะฯ)
-- ==========================================
('TRANSIT_STATION', 'bts_khu_khot', '{"th": "คูคต", "en": "Khu Khot", "cn": "库括 (Khu Khot)", "ru": "Кхукхот"}', true, 10, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_yaek_kor_por_aor', '{"th": "แยก คปอ.", "en": "Yaek Kor Por Aor", "cn": "阔波奥路口 (Yaek Kor Por Aor)", "ru": "Йек Кор Пор Аор"}', true, 12, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_royal_thai_air_force_museum', '{"th": "พิพิธภัณฑ์กองทัพอากาศ", "en": "Royal Thai Air Force Museum", "cn": "空军博物馆 (Royal Thai Air Force Museum)", "ru": "Музей Королевских ВВС"}', true, 14, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_bhumibol_adulyadej_hospital', '{"th": "โรงพยาบาลภูมิพลอดุลยเดช", "en": "Bhumibol Adulyadej Hospital", "cn": "普密蓬医院 (Bhumibol Adulyadej Hospital)", "ru": "Больница Пхумипон Адульядет"}', true, 16, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_saphan_mai', '{"th": "สะพานใหม่", "en": "Saphan Mai", "cn": "沙潘迈 (Saphan Mai)", "ru": "Сапхан Май"}', true, 18, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_phahon_yothin_59', '{"th": "พหลโยธิน 59", "en": "Phahon Yothin 59", "cn": "拍红裕廷59 (Phahon Yothin 59)", "ru": "Пхахонйотхин 59"}', true, 20, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_sai_yud', '{"th": "สายหยุด", "en": "Sai Yud", "cn": "赛育 (Sai Yud)", "ru": "Сай Йуд"}', true, 22, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_wat_phra_sri_mahathat', '{"th": "วัดพระศรีมหาธาตุ", "en": "Wat Phra Sri Mahathat", "cn": "帕斯里玛哈他寺 (Wat Phra Sri Mahathat)", "ru": "Ват Пхра Шри Махатхат"}', true, 24, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_11th_infantry_regiment', '{"th": "กรมทหารราบที่ 11", "en": "11th Infantry Regiment", "cn": "第11步兵团 (11th Infantry Regiment)", "ru": "11-й пехотный полк"}', true, 26, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_bang_bua', '{"th": "บางบัว", "en": "Bang Bua", "cn": "邦博 (Bang Bua)", "ru": "Банг Буа"}', true, 28, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_royal_forest_department', '{"th": "กรมป่าไม้", "en": "Royal Forest Department", "cn": "森林局 (Royal Forest Department)", "ru": "Лесной департамент"}', true, 30, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_kasetsart_university', '{"th": "มหาวิทยาลัยเกษตรศาสตร์", "en": "Kasetsart University", "cn": "农业大学 (Kasetsart University)", "ru": "Университет Касетсарт"}', true, 32, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_sena_nikhom', '{"th": "เสนานิคม", "en": "Sena Nikhom", "cn": "瑟纳尼空 (Sena Nikhom)", "ru": "Сена Никхом"}', true, 34, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_ratchayothin', '{"th": "รัชโยธิน", "en": "Ratchayothin", "cn": "拉差裕廷 (Ratchayothin)", "ru": "Ратчайотин"}', true, 36, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_phahon_yothin_24', '{"th": "พหลโยธิน 24", "en": "Phahon Yothin 24", "cn": "拍红裕廷24 (Phahon Yothin 24)", "ru": "Пхахонйотхин 24"}', true, 38, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_ha_yaek_lat_phrao', '{"th": "ห้าแยกลาดพร้าว", "en": "Ha Yaek Lat Phrao", "cn": "叻抛五叉路口 (Ha Yaek Lat Phrao)", "ru": "Пятиуличный Латпхрау"}', true, 40, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_mo_chit', '{"th": "หมอชิต", "en": "Mo Chit", "cn": "蒙奇 (Mo Chit)", "ru": "Мочит"}', true, 42, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_saphan_khwai', '{"th": "สะพานควาย", "en": "Saphan Khwai", "cn": "水牛桥 (Saphan Khwai)", "ru": "Сапханкхуай"}', true, 44, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_ari', '{"th": "อารีย์", "en": "Ari", "cn": "阿里 (Ari)", "ru": "Ари"}', true, 46, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_sanam_pao', '{"th": "สนามเป้า", "en": "Sanam Pao", "cn": "沙南包 (Sanam Pao)", "ru": "Санампао"}', true, 48, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_victory_monument', '{"th": "อนุสาวรีย์ชัยสมรภูมิ", "en": "Victory Monument", "cn": "胜利纪念碑 (Victory Monument)", "ru": "Монумент Победы"}', true, 50, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_phaya_thai', '{"th": "พญาไท", "en": "Phaya Thai", "cn": "披耶泰 (Phaya Thai)", "ru": "Пхая Тхаи"}', true, 52, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_ratchathewi', '{"th": "ราชเทวี", "en": "Ratchathewi", "cn": "拉差贴威 (Ratchathewi)", "ru": "Ратчатхеви"}', true, 54, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_siam', '{"th": "สยาม", "en": "Siam", "cn": "暹罗 (Siam)", "ru": "Сиам"}', true, 56, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_chit_lom', '{"th": "ชิดลม", "en": "Chit Lom", "cn": "奇隆 (Chit Lom)", "ru": "Читлом"}', true, 58, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_phloen_chit', '{"th": "เพลินจิต", "en": "Phloen Chit", "cn": "菲隆奇 (Phloen Chit)", "ru": "Пхленчит"}', true, 60, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_nana', '{"th": "นานา", "en": "Nana", "cn": "那那 (Nana)", "ru": "Нана"}', true, 62, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_asok', '{"th": "อโศก", "en": "Asok", "cn": "阿索克 (Asok)", "ru": "Асок"}', true, 64, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_phrom_phong', '{"th": "พร้อมพงษ์", "en": "Phrom Phong", "cn": "蓬蓬 (Phrom Phong)", "ru": "Промпонг"}', true, 66, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_thong_lo', '{"th": "ทองหล่อ", "en": "Thong Lo", "cn": "东罗 (Thong Lo)", "ru": "Тонгло"}', true, 68, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_ekkamai', '{"th": "เอกมัย", "en": "Ekkamai", "cn": "伊卡迈 (Ekkamai)", "ru": "Эккамай"}', true, 70, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_phra_khanong', '{"th": "พระโขนง", "en": "Phra Khanong", "cn": "帕卡隆 (Phra Khanong)", "ru": "Пракханонг"}', true, 72, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_on_nut', '{"th": "อ่อนนุช", "en": "On Nut", "cn": "安努 (On Nut)", "ru": "Оннут"}', true, 74, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_bang_chak', '{"th": "บางจาก", "en": "Bang Chak", "cn": "邦泽 (Bang Chak)", "ru": "Бангчак"}', true, 76, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_punnawithi', '{"th": "ปุณณวิถี", "en": "Punnawithi", "cn": "普那威提 (Punnawithi)", "ru": "Пуннавитхи"}', true, 78, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_udom_suk', '{"th": "อุดมสุข", "en": "Udom Suk", "cn": "乌东素 (Udom Suk)", "ru": "Удомсук"}', true, 80, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_bang_na', '{"th": "บางนา", "en": "Bang Na", "cn": "班纳 (Bang Na)", "ru": "Бангна"}', true, 82, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_bearing', '{"th": "แบริ่ง", "en": "Bearing", "cn": "贝林 (Bearing)", "ru": "Беринг"}', true, 84, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_samrong', '{"th": "สำโรง", "en": "Samrong", "cn": "三榕 (Samrong)", "ru": "Самронг"}', true, 86, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_pu_chao', '{"th": "ปู่เจ้า", "en": "Pu Chao", "cn": "普照 (Pu Chao)", "ru": "Пу Чао"}', true, 88, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_chang_erawan', '{"th": "ช้างเอราวัณ", "en": "Chang Erawan", "cn": "爱侣湾 (Chang Erawan)", "ru": "Чанг Эраван"}', true, 90, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_royal_thai_naval_academy', '{"th": "โรงเรียนนายเรือ", "en": "Royal Thai Naval Academy", "cn": "海军学院 (Royal Thai Naval Academy)", "ru": "Военно-морская академия"}', true, 92, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_pak_nam', '{"th": "ปากน้ำ", "en": "Pak Nam", "cn": "北榄 (Pak Nam)", "ru": "Пакнам"}', true, 94, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_srinagarindra', '{"th": "ศรีนครินทร์", "en": "Srinagarindra", "cn": "诗纳卡琳 (Srinagarindra)", "ru": "Шринагариндра"}', true, 96, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_phraek_sa', '{"th": "แพรกษา", "en": "Phraek Sa", "cn": "佩沙 (Phraek Sa)", "ru": "Пхрэкса"}', true, 98, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_sai_luat', '{"th": "สายลวด", "en": "Sai Luat", "cn": "赛罗 (Sai Luat)", "ru": "Сай Луат"}', true, 100, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_kheha', '{"th": "เคหะฯ", "en": "Kheha", "cn": "凯哈 (Kheha)", "ru": "Кеха"}', true, 102, '{"transit_type": "BTS"}'),

-- ==========================================
-- 🟢 BTS Silom Line (ครบทุกสถานี)
-- ==========================================
('TRANSIT_STATION', 'bts_national_stadium', '{"th": "สนามกีฬาแห่งชาติ", "en": "National Stadium", "cn": "国家体育馆 (National Stadium)", "ru": "Национальный стадион"}', true, 150, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_ratchadamri', '{"th": "ราชดำริ", "en": "Ratchadamri", "cn": "拉差丹利 (Ratchadamri)", "ru": "Ратчадамри"}', true, 155, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_sala_daeng', '{"th": "ศาลาแดง", "en": "Sala Daeng", "cn": "莎拉当 (Sala Daeng)", "ru": "Саладаенг"}', true, 160, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_chong_nonsi', '{"th": "ช่องนนทรี", "en": "Chong Nonsi", "cn": "钟那席 (Chong Nonsi)", "ru": "Чонг Нонси"}', true, 165, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_saint_louis', '{"th": "เซนต์หลุยส์", "en": "Saint Louis", "cn": "圣路易斯 (Saint Louis)", "ru": "Сент-Луис"}', true, 170, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_surasak', '{"th": "สุรศักดิ์", "en": "Surasak", "cn": "苏拉萨 (Surasak)", "ru": "Сурасак"}', true, 175, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_saphan_taksin', '{"th": "สะพานตากสิน", "en": "Saphan Taksin", "cn": "郑皇桥 (Saphan Taksin)", "ru": "Сапхан Таксин"}', true, 180, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_krung_thon_buri', '{"th": "กรุงธนบุรี", "en": "Krung Thon Buri", "cn": "功吞武里 (Krung Thon Buri)", "ru": "Крунг Тхон Бури"}', true, 185, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_wongwian_yai', '{"th": "วงเวียนใหญ่", "en": "Wongwian Yai", "cn": "大环圈 (Wongwian Yai)", "ru": "Вонгвиан Яй"}', true, 190, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_pho_nimit', '{"th": "โพธิ์นิมิตร", "en": "Pho Nimit", "cn": "菩尼密 (Pho Nimit)", "ru": "Пхо Нимит"}', true, 191, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_talat_phlu', '{"th": "ตลาดพลู", "en": "Talat Phlu", "cn": "哒叻普 (Talat Phlu)", "ru": "Талат Пхлу"}', true, 192, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_wutthakat', '{"th": "วุฒากาศ", "en": "Wutthakat", "cn": "武他甲 (Wutthakat)", "ru": "Вуттхакат"}', true, 193, '{"transit_type": "BTS"}'),
('TRANSIT_STATION', 'bts_bang_wa', '{"th": "บางหว้า", "en": "Bang Wa", "cn": "邦瓦 (Bang Wa)", "ru": "Бангва"}', true, 194, '{"transit_type": "BTS"}'),

-- ==========================================
-- 🔵 MRT Blue Line (ครบทุกสถานี)
-- ==========================================
('TRANSIT_STATION', 'mrt_tha_phra', '{"th": "ท่าพระ", "en": "Tha Phra", "cn": "塔帕 (Tha Phra)", "ru": "Тха Пхра"}', true, 200, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_charan_13', '{"th": "จรัญฯ 13", "en": "Charan 13", "cn": "乍兰13 (Charan 13)", "ru": "Чаран 13"}', true, 202, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_fai_chai', '{"th": "ไฟฉาย", "en": "Fai Chai", "cn": "发猜 (Fai Chai)", "ru": "Фай Чай"}', true, 204, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_bang_khun_non', '{"th": "บางขุนนนท์", "en": "Bang Khun Non", "cn": "邦坤农 (Bang Khun Non)", "ru": "Бангкхуннон"}', true, 206, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_bang_yi_khan', '{"th": "บางยี่ขัน", "en": "Bang Yi Khan", "cn": "邦伊坎 (Bang Yi Khan)", "ru": "Банг Йи Кхан"}', true, 208, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_sirindhorn', '{"th": "สิรินธร", "en": "Sirindhorn", "cn": "诗琳通 (Sirindhorn)", "ru": "Сириндхорн"}', true, 210, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_bang_phlat', '{"th": "บางพลัด", "en": "Bang Phlat", "cn": "邦帕 (Bang Phlat)", "ru": "Банг Пхлат"}', true, 212, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_bang_o', '{"th": "บางอ้อ", "en": "Bang O", "cn": "邦奥 (Bang O)", "ru": "Банго"}', true, 214, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_bang_po', '{"th": "บางโพ", "en": "Bang Pho", "cn": "邦坡 (Bang Pho)", "ru": "Бангпхо"}', true, 216, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_tao_poon_blue', '{"th": "เตาปูน (สายสีน้ำเงิน)", "en": "Tao Poon (Blue Line)", "cn": "涛本 (蓝线) (Tao Poon (Blue Line))", "ru": "Таопун (Синяя линия)"}', true, 218, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_bang_sue', '{"th": "บางซื่อ", "en": "Bang Sue", "cn": "邦士 (Bang Sue)", "ru": "Бангсу"}', true, 220, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_kamphaeng_phet', '{"th": "กำแพงเพชร", "en": "Kamphaeng Phet", "cn": "甘烹碧 (Kamphaeng Phet)", "ru": "Кампхенгпхет"}', true, 222, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_chatuchak_park', '{"th": "สวนจตุจักร", "en": "Chatuchak Park", "cn": "乍都乍公园 (Chatuchak Park)", "ru": "Парк Чатучак"}', true, 224, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_phahon_yothin', '{"th": "พหลโยธิน", "en": "Phahon Yothin", "cn": "拍朋裕廷 (Phahon Yothin)", "ru": "Пхахонйотхин"}', true, 226, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_lat_phrao', '{"th": "ลาดพร้าว", "en": "Lat Phrao", "cn": "叻抛 (Lat Phrao)", "ru": "Латпхрау"}', true, 228, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_ratchadaphisek', '{"th": "รัชดาภิเษก", "en": "Ratchadaphisek", "cn": "拉差达披色 (Ratchadaphisek)", "ru": "Ратчадапхисек"}', true, 230, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_sutthisan', '{"th": "สุทธิสาร", "en": "Sutthisan", "cn": "苏地讪 (Sutthisan)", "ru": "Сутхисан"}', true, 232, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_huai_khwang', '{"th": "ห้วยขวาง", "en": "Huai Khwang", "cn": "汇权 (Huai Khwang)", "ru": "Хуайкхванг"}', true, 234, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_thailand_cultural_centre', '{"th": "ศูนย์วัฒนธรรมแห่งประเทศไทย", "en": "Thailand Cultural Centre", "cn": "泰国文化中心 (Thailand Cultural Centre)", "ru": "Культурный центр Таиланда"}', true, 236, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_phra_ram_9', '{"th": "พระราม 9", "en": "Phra Ram 9", "cn": "帕蓝9 (Phra Ram 9)", "ru": "Пхра Рам 9"}', true, 238, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_phetchaburi', '{"th": "เพชรบุรี", "en": "Phetchaburi", "cn": "碧武里 (Phetchaburi)", "ru": "Пхетчабури"}', true, 240, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_sukhumvit', '{"th": "สุขุมวิท", "en": "Sukhumvit", "cn": "素坤逸 (Sukhumvit)", "ru": "Сукхумвит"}', true, 242, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_queen_sirikit', '{"th": "ศูนย์การประชุมแห่งชาติสิริกิติ์", "en": "Queen Sirikit National Convention Centre", "cn": "诗丽吉会展中心 (Queen Sirikit National Convention Centre)", "ru": "Центр Королевы Сирикит"}', true, 244, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_khlong_toei', '{"th": "คลองเตย", "en": "Khlong Toei", "cn": "孔提 (Khlong Toei)", "ru": "Клонгтей"}', true, 246, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_lumphini', '{"th": "ลุมพินี", "en": "Lumphini", "cn": "伦披尼 (Lumphini)", "ru": "Лумпхини"}', true, 248, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_silom', '{"th": "สีลม", "en": "Silom", "cn": "席隆 (Silom)", "ru": "Силом"}', true, 250, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_sam_yan', '{"th": "สามย่าน", "en": "Sam Yan", "cn": "山燕 (Sam Yan)", "ru": "Самьян"}', true, 252, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_hua_lamphong', '{"th": "หัวลำโพง", "en": "Hua Lamphong", "cn": "华南蓬 (Hua Lamphong)", "ru": "Хуалампхонг"}', true, 254, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_wat_mangkon', '{"th": "วัดมังกร", "en": "Wat Mangkon", "cn": "龙莲寺 (Wat Mangkon)", "ru": "Ват Мангкон"}', true, 256, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_sam_yot', '{"th": "สามยอด", "en": "Sam Yot", "cn": "三峰 (Sam Yot)", "ru": "Сам Йот"}', true, 258, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_sanam_chai', '{"th": "สนามไชย", "en": "Sanam Chai", "cn": "沙南猜 (Sanam Chai)", "ru": "Санам Чай"}', true, 260, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_itsaraphap', '{"th": "อิสรภาพ", "en": "Itsaraphap", "cn": "自由路 (Itsaraphap)", "ru": "Итсарапхап"}', true, 262, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_bang_phai', '{"th": "บางไผ่", "en": "Bang Phai", "cn": "邦派 (Bang Phai)", "ru": "Банг Пхай"}', true, 264, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_phasi_charoen', '{"th": "ภาษีเจริญ", "en": "Phasi Charoen", "cn": "帕世乍能 (Phasi Charoen)", "ru": "Пхаси Чароен"}', true, 266, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_bang_khae', '{"th": "บางแค", "en": "Bang Khae", "cn": "邦凯 (Bang Khae)", "ru": "Банг Кэ"}', true, 268, '{"transit_type": "MRT"}'),
('TRANSIT_STATION', 'mrt_lak_song', '{"th": "หลักสอง", "en": "Lak Song", "cn": "叻松 (Lak Song)", "ru": "Лак Сонг"}', true, 270, '{"transit_type": "MRT"}'),

-- ==========================================
-- 🟣 MRT Purple Line (ครบทุกสถานี)
-- ==========================================
('TRANSIT_STATION', 'mrt_khlong_bang_phai', '{"th": "คลองบางไผ่", "en": "Khlong Bang Phai", "cn": "空邦派 (Khlong Bang Phai)", "ru": "Клонг Банг Пхай"}', true, 300, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_talad_bang_yai', '{"th": "ตลาดบางใหญ่", "en": "Talat Bang Yai", "cn": "邦艾市场 (Talat Bang Yai)", "ru": "Талат Банг Яй"}', true, 302, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_sam_yaek_bang_yai', '{"th": "สามแยกบางใหญ่", "en": "Sam Yaek Bang Yai", "cn": "邦艾三岔路口 (Sam Yaek Bang Yai)", "ru": "Сам Йек Банг Яй"}', true, 304, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_bang_rak_yai', '{"th": "บางรักใหญ่", "en": "Bang Rak Yai", "cn": "邦叻亚 (Bang Rak Yai)", "ru": "Банг Рак Яй"}', true, 306, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_bang_rak_noi_tha_it', '{"th": "บางรักน้อยท่าอิฐ", "en": "Bang Rak Noi Tha It", "cn": "邦叻内塔伊 (Bang Rak Noi Tha It)", "ru": "Банг Рак Ной Тха Ит"}', true, 308, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_sai_ma', '{"th": "ไทรม้า", "en": "Sai Ma", "cn": "赛马 (Sai Ma)", "ru": "Сай Ма"}', true, 310, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_phra_nang_klao', '{"th": "สะพานพระนั่งเกล้า", "en": "Phra Nang Klao Bridge", "cn": "帕喃告大桥 (Phra Nang Klao Bridge)", "ru": "Мост Пхра Нанг Клао"}', true, 312, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_yaek_nonthaburi_1', '{"th": "แยกนนทบุรี 1", "en": "Yaek Nonthaburi 1", "cn": "暖武里1交叉口 (Yaek Nonthaburi 1)", "ru": "Перекресток Нонтхабури 1"}', true, 314, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_bang_krasor', '{"th": "บางกระสอ", "en": "Bang Krasor", "cn": "班格索 (Bang Krasor)", "ru": "Бангкрасо"}', true, 316, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_nonthaburi_civic_center', '{"th": "ศูนย์ราชการนนทบุรี", "en": "Nonthaburi Civic Center", "cn": "暖武里市政中心 (Nonthaburi Civic Center)", "ru": "Гражданский центр Нонтхабури"}', true, 318, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_ministry_of_public_health', '{"th": "กระทรวงสาธารณสุข", "en": "Ministry of Public Health", "cn": "卫生部 (Ministry of Public Health)", "ru": "Министерство здравоохранения"}', true, 320, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_yaek_tiwanon', '{"th": "แยกติวานนท์", "en": "Yaek Tiwanon", "cn": "提瓦农路口 (Yaek Tiwanon)", "ru": "Перекресток Тиванон"}', true, 322, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_wongsawan', '{"th": "วงศ์สว่าง", "en": "Wongsawang", "cn": "翁萨旺 (Wongsawang)", "ru": "Вонгсаванг"}', true, 324, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_bang_son', '{"th": "บางซ่อน", "en": "Bang Son", "cn": "挽松 (Bang Son)", "ru": "Банг Сон"}', true, 326, '{"transit_type": "MRT_PURPLE"}'),
('TRANSIT_STATION', 'mrt_tao_poon', '{"th": "เตาปูน", "en": "Tao Poon", "cn": "涛本 (Tao Poon)", "ru": "Таопун"}', true, 328, '{"transit_type": "MRT_PURPLE"}'),

-- ==========================================
-- 🟡 MRT Yellow Line (ครบ 23 สถานี ลาดพร้าว - สำโรง)
-- ==========================================
('TRANSIT_STATION', 'mrt_yellow_lat_phrao', '{"th": "ลาดพร้าว (สายสีเหลือง)", "en": "Lat Phrao (Yellow Line)", "cn": "叻抛 (黄线) (Lat Phrao (Yellow Line))", "ru": "Латпхрау (Желтая линия)"}', true, 400, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_phawana', '{"th": "ภาวนา", "en": "Phawana", "cn": "帕瓦纳 (Phawana)", "ru": "Пхавана"}', true, 402, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_chok_chai_4', '{"th": "โชคชัย 4", "en": "Chok Chai 4", "cn": "措猜 4 (Chok Chai 4)", "ru": "Чокчай 4"}', true, 404, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_lat_phrao_71', '{"th": "ลาดพร้าว 71", "en": "Lat Phrao 71", "cn": "叻抛71 (Lat Phrao 71)", "ru": "Латпхрау 71"}', true, 406, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_lat_phrao_83', '{"th": "ลาดพร้าว 83", "en": "Lat Phrao 83", "cn": "叻抛83 (Lat Phrao 83)", "ru": "Латпхрау 83"}', true, 408, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_mahatthai', '{"th": "มหาดไทย", "en": "Mahatthai", "cn": "玛哈泰 (Mahatthai)", "ru": "Махаттхай"}', true, 410, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_lat_phrao_101', '{"th": "ลาดพร้าว 101", "en": "Lat Phrao 101", "cn": "叻抛101 (Lat Phrao 101)", "ru": "Латпхрау 101"}', true, 412, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_bang_kapi', '{"th": "บางกะปิ", "en": "Bang Kapi", "cn": "邦甲比 (Bang Kapi)", "ru": "Бангкапи"}', true, 414, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_lam_sali', '{"th": "แยกลำสาลี", "en": "Yaek Lam Sali", "cn": "蓝萨利交叉口 (Yaek Lam Sali)", "ru": "Йек Лам Сали"}', true, 416, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_si_kritha', '{"th": "ศรีกรีฑา", "en": "Si Kritha", "cn": "诗格里达 (Si Kritha)", "ru": "Шри Крита"}', true, 418, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_phatthanakan', '{"th": "พัฒนาการ", "en": "Phattanakan", "cn": "发展路 (Phattanakan)", "ru": "Пхаттханакан"}', true, 420, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_kalantan', '{"th": "กลันตัน", "en": "Kalantan", "cn": "格兰丹 (Kalantan)", "ru": "Калантан"}', true, 422, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_si_nut', '{"th": "ศรีนุช", "en": "Si Nut", "cn": "诗努 (Si Nut)", "ru": "Шринут"}', true, 424, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_srinagarindra', '{"th": "ศรีนครินทร์ 38", "en": "Srinagarindra 38", "cn": "诗纳卡琳38 (Srinagarindra 38)", "ru": "Шринагариндра 38"}', true, 426, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_suan_luang_rama_9', '{"th": "สวนหลวง ร.9", "en": "Suan Luang Rama IX", "cn": "九世王公园 (Suan Luang Rama IX)", "ru": "Парк Рамы IX"}', true, 428, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_si_udom', '{"th": "ศรีอุดม", "en": "Si Udom", "cn": "诗乌东 (Si Udom)", "ru": "Шри Удом"}', true, 430, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_si_iam', '{"th": "ศรีเอี่ยม", "en": "Si Iam", "cn": "诗艾姆 (Si Iam)", "ru": "Шри-иам"}', true, 432, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_si_la_salle', '{"th": "ศรีลาซาล", "en": "Si La Salle", "cn": "诗拉萨 (Si La Salle)", "ru": "Шри Ла Саль"}', true, 434, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_si_bearing', '{"th": "ศรีแบริ่ง", "en": "Si Bearing", "cn": "诗贝林 (Si Bearing)", "ru": "Шри Беринг"}', true, 436, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_si_dan', '{"th": "ศรีด่าน", "en": "Si Dan", "cn": "诗丹 (Si Dan)", "ru": "Шри Дан"}', true, 438, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_si_thepha', '{"th": "ศรีเทพา", "en": "Si Thepha", "cn": "诗贴帕 (Si Thepha)", "ru": "Шри Тхепха"}', true, 440, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_thipphawan', '{"th": "ทิพวัล", "en": "Thipphawan", "cn": "提帕万 (Thipphawan)", "ru": "Тхиппхаван"}', true, 442, '{"transit_type": "MRT_YELLOW"}'),
('TRANSIT_STATION', 'mrt_samrong_yellow', '{"th": "สำโรง (สายสีเหลือง)", "en": "Samrong (Yellow Line)", "cn": "三榕 (黄线) (Samrong (Yellow Line))", "ru": "Самронг (Желтая)"}', true, 444, '{"transit_type": "MRT_YELLOW"}'),

-- ==========================================
-- 🩷 MRT Pink Line (ครบ 30 สถานี ศูนย์ราชการนนทบุรี - มีนบุรี)
-- ==========================================
('TRANSIT_STATION', 'mrt_pink_civic_center', '{"th": "ศูนย์ราชการนนทบุรี (สายสีชมพู)", "en": "Nonthaburi Civic Center (Pink Line)", "cn": "暖武里市政中心 (粉红线) (Nonthaburi Civic Center (Pink Line))", "ru": "Гражданский центр Нонтхабури (Розовая)"}', true, 460, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_khae_rai', '{"th": "แคราย", "en": "Khae Rai", "cn": "开莱 (Khae Rai)", "ru": "Кхэрай"}', true, 462, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_sanambin_nam', '{"th": "สนามบินน้ำ", "en": "Sanambin Nam", "cn": "沙南宾南 (Sanambin Nam)", "ru": "Санамбин Нам"}', true, 464, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_samakkhi', '{"th": "สามัคคี", "en": "Samakkhi", "cn": "萨马基 (Samakkhi)", "ru": "Самаккхи"}', true, 466, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_royal_irrigation_department', '{"th": "กรมชลประทาน", "en": "Royal Irrigation Department", "cn": "皇家灌溉局 (Royal Irrigation Department)", "ru": "Королевский департамент ирригации"}', true, 468, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_yaek_pak_kret', '{"th": "แยกปากเกร็ด", "en": "Yaek Pak Kret", "cn": "白革路口 (Yaek Pak Kret)", "ru": "Йек Паккрет"}', true, 470, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_pak_kret_bypass', '{"th": "เลี่ยงเมืองปากเกร็ด", "en": "Pak Kret Bypass", "cn": "白革绕道 (Pak Kret Bypass)", "ru": "Объезд Паккрет"}', true, 472, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_chaeng_watthana_pak_kret_28', '{"th": "แจ้งวัฒนะ-ปากเกร็ด 28", "en": "Chaeng Watthana-Pak Kret 28", "cn": "珍瓦塔纳-白革28 (Chaeng Watthana-Pak Kret 28)", "ru": "Ченгваттхана-Паккрет 28"}', true, 474, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_si_rat', '{"th": "ศรีรัช", "en": "Si Rat", "cn": "诗叻 (Si Rat)", "ru": "Шри Рат"}', true, 476, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_mueang_thong_thani', '{"th": "เมืองทองธานี", "en": "Mueang Thong Thani", "cn": "蒙通他尼 (Mueang Thong Thani)", "ru": "Муанг Тхонг Тхани"}', true, 478, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_chaeng_watthana_14', '{"th": "แจ้งวัฒนะ 14", "en": "Chaeng Watthana 14", "cn": "珍瓦塔纳14 (Chaeng Watthana 14)", "ru": "Ченгваттхана 14"}', true, 480, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_government_complex', '{"th": "ศูนย์ราชการเฉลิมพระเกียรติ", "en": "Government Complex", "cn": "政府综合大楼 (Government Complex)", "ru": "Правительственный комплекс"}', true, 482, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_national_telecom', '{"th": "โทรคมนาคมแห่งชาติ", "en": "National Telecom", "cn": "国家电信中心 (National Telecom)", "ru": "Национальный Телеком"}', true, 484, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_lak_si', '{"th": "หลักสี่ (สายสีชมพู)", "en": "Lak Si (Pink Line)", "cn": "拉席 (粉红线) (Lak Si (Pink Line))", "ru": "Лакси (Розовая)"}', true, 486, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_rajabhat_phranakhon', '{"th": "ราชภัฏพระนคร", "en": "Rajabhat Phranakhon", "cn": "拍那空皇家大学 (Rajabhat Phranakhon)", "ru": "Раджабхат Пхранакхон"}', true, 488, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_wat_phra_sri_mahathat_pink', '{"th": "วัดพระศรีมหาธาตุ (สายสีชมพู)", "en": "Wat Phra Sri Mahathat (Pink Line)", "cn": "帕斯里玛哈他寺 (粉红线) (Wat Phra Sri Mahathat (Pink Line))", "ru": "Ват Пхра Шри Махатхат (Розовая)"}', true, 490, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_ram_inthra_3', '{"th": "รามอินทรา 3", "en": "Ram Inthra 3", "cn": "兰茵他 3 (Ram Inthra 3)", "ru": "Рам Интхра 3"}', true, 492, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_lat_pla_khao', '{"th": "ลาดปลาเค้า", "en": "Lat Pla Khao", "cn": "拉巴考 (Lat Pla Khao)", "ru": "Лат Пла Кхао"}', true, 494, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_ram_inthra_kor_mor_4', '{"th": "รามอินทรา กม.4", "en": "Ram Inthra Kor Mor 4", "cn": "兰茵他4公里 (Ram Inthra Kor Mor 4)", "ru": "Рам Интхра Кор Мор 4"}', true, 496, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_maiyalap', '{"th": "มัยลาภ", "en": "Maiyalap", "cn": "迈亚腊 (Maiyalap)", "ru": "Майялап"}', true, 498, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_vacharaphol', '{"th": "วัชรพล", "en": "Vacharaphol", "cn": "瓦查拉蓬 (Vacharaphol)", "ru": "Вачарапхон"}', true, 500, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_ram_inthra_kor_mor_6', '{"th": "รามอินทรา กม.6", "en": "Ram Inthra Kor Mor 6", "cn": "兰茵他6公里 (Ram Inthra Kor Mor 6)", "ru": "Рам Интхра Кор Мор 6"}', true, 502, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_khu_bon', '{"th": "คู้บอน", "en": "Khu Bon", "cn": "库本 (Khu Bon)", "ru": "Кхубон"}', true, 504, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_ram_inthra_kor_mor_9', '{"th": "รามอินทรา กม.9", "en": "Ram Inthra Kor Mor 9", "cn": "兰茵他9公里 (Ram Inthra Kor Mor 9)", "ru": "Рам Интхра Кор Мор 9"}', true, 506, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_outer_ring_road_ram_inthra', '{"th": "วงแหวนรามอินทรา", "en": "Outer Ring Road - Ram Inthra", "cn": "兰茵他外环路 (Outer Ring Road - Ram Inthra)", "ru": "Внешняя кольцевая - Рам Интхра"}', true, 508, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_nopparat', '{"th": "นพรัตน์", "en": "Nopparat", "cn": "诺帕拉 (Nopparat)", "ru": "Ноппарат"}', true, 510, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_bang_chan', '{"th": "บางชัน", "en": "Bang Chan", "cn": "邦灿 (Bang Chan)", "ru": "Банг Чан"}', true, 512, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_setthabutbamphen', '{"th": "เศรษฐบุตรบำเพ็ญ", "en": "Setthabutbamphen", "cn": "塞塔布班彭 (Setthabutbamphen)", "ru": "Сеттхабутбампхен"}', true, 514, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_min_buri_market', '{"th": "ตลาดมีนบุรี", "en": "Min Buri Market", "cn": "民武里市场 (Min Buri Market)", "ru": "Рынок Минбури"}', true, 516, '{"transit_type": "MRT_PINK"}'),
('TRANSIT_STATION', 'mrt_min_buri', '{"th": "มีนบุรี", "en": "Min Buri", "cn": "民武里 (Min Buri)", "ru": "Минбури"}', true, 518, '{"transit_type": "MRT_PINK"}'),

-- ==========================================
-- ✈️ Airport Rail Link (ARL)
-- ==========================================
('TRANSIT_STATION', 'arl_phaya_thai', '{"th": "พญาไท (ARL)", "en": "Phaya Thai (ARL)", "cn": "披耶泰 (ARL) (Phaya Thai (ARL))", "ru": "Пхая Тхаи (ARL)"}', true, 600, '{"transit_type": "ARL"}'),
('TRANSIT_STATION', 'arl_ratchaprarop', '{"th": "ราชปรารภ", "en": "Ratchaprarop", "cn": "拉差巴洛 (Ratchaprarop)", "ru": "Ратчапрароп"}', true, 602, '{"transit_type": "ARL"}'),
('TRANSIT_STATION', 'arl_makkasan', '{"th": "มักกะสัน (ARL)", "en": "Makkasan (ARL)", "cn": "目甲讪 (ARL) (Makkasan (ARL))", "ru": "Маккасан (ARL)"}', true, 604, '{"transit_type": "ARL"}'),
('TRANSIT_STATION', 'arl_ramkhamhaeng', '{"th": "รามคำแหง", "en": "Ramkhamhaeng (ARL)", "cn": "兰甘亨 (ARL) (Ramkhamhaeng (ARL))", "ru": "Рамкхамхенг"}', true, 606, '{"transit_type": "ARL"}'),
('TRANSIT_STATION', 'arl_hua_mak', '{"th": "หัวหมาก (ARL)", "en": "Hua Mak (ARL)", "cn": "华目 (ARL) (Hua Mak (ARL))", "ru": "Хуа Мак (ARL)"}', true, 608, '{"transit_type": "ARL"}'),
('TRANSIT_STATION', 'arl_ban_thap_chang', '{"th": "บ้านทับช้าง", "en": "Ban Thap Chang", "cn": "班塔昌 (Ban Thap Chang)", "ru": "Бан Тхап Чанг"}', true, 610, '{"transit_type": "ARL"}'),
('TRANSIT_STATION', 'arl_lat_krabang', '{"th": "ลาดกระบัง", "en": "Lat Krabang (ARL)", "cn": "拉格拉邦 (ARL) (Lat Krabang (ARL))", "ru": "Латкрабанг"}', true, 612, '{"transit_type": "ARL"}'),
('TRANSIT_STATION', 'arl_suvarnabhumi', '{"th": "สุวรรณภูมิ", "en": "Suvarnabhumi Airport", "cn": "素万那普机场 (Suvarnabhumi Airport)", "ru": "Аэропорт Суварнабхуми"}', true, 614, '{"transit_type": "ARL"}'),

-- ==========================================
-- 🪙 Gold Line
-- ==========================================
('TRANSIT_STATION', 'gold_krung_thon_buri', '{"th": "กรุงธนบุรี (สายสีทอง)", "en": "Krung Thon Buri (Gold)", "cn": "吞武里 (金线) (Krung Thon Buri (Gold))", "ru": "Крунг Тхон Бури (Золотая)"}', true, 650, '{"transit_type": "GOLD"}'),
('TRANSIT_STATION', 'gold_charoen_nakhon', '{"th": "เจริญนคร (ไอคอนสยาม)", "en": "Charoen Nakhon (IconSiam)", "cn": "佳能那空 (IconSiam) (Charoen Nakhon (IconSiam))", "ru": "Чароен Накхон (ИконСиам)"}', true, 652, '{"transit_type": "GOLD"}'),
('TRANSIT_STATION', 'gold_khlong_san', '{"th": "คลองสาน", "en": "Khlong San", "cn": "空讪 (Khlong San)", "ru": "Клонг Сан"}', true, 654, '{"transit_type": "GOLD"}'),

-- ==========================================
-- 🔴 SRT Red Line (Dark/Light - ครบ)
-- ==========================================
('TRANSIT_STATION', 'srt_taling_chan', '{"th": "ตลิ่งชัน", "en": "Taling Chan", "cn": "大林江 (Taling Chan)", "ru": "Талинг Чан"}', true, 700, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_bang_bamru', '{"th": "บางบำหรุ", "en": "Bang Bamru", "cn": "邦班鲁 (Bang Bamru)", "ru": "Банг Бамру"}', true, 702, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_bang_son', '{"th": "บางซ่อน (สายสีแดง)", "en": "Bang Son (Red Line)", "cn": "挽松 (红线) (Bang Son (Red Line))", "ru": "Банг Сон (Красная линия)"}', true, 704, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_krung_thep_aphiwat', '{"th": "สถานีกลางกรุงเทพอภิวัฒน์", "en": "Krung Thep Aphiwat Central Terminal", "cn": "曼谷阿皮瓦中央车站 (Krung Thep Aphiwat Central Terminal)", "ru": "Центральный вокзал Крунг Тхеп Апхиват"}', true, 706, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_chatuchak', '{"th": "จตุจักร (สายสีแดง)", "en": "Chatuchak (Red Line)", "cn": "乍都乍 (红线) (Chatuchak (Red Line))", "ru": "Чатучак (Красная линия)"}', true, 708, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_wat_samian_nari', '{"th": "วัดเสมียนนารี", "en": "Wat Samian Nari", "cn": "萨米安娜丽寺 (Wat Samian Nari)", "ru": "Ват Самиан Нари"}', true, 710, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_bang_khen', '{"th": "บางเขน", "en": "Bang Khen", "cn": "邦肯 (Bang Khen)", "ru": "Банг Кхен"}', true, 712, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_thung_song_hong', '{"th": "ทุ่งสองห้อง", "en": "Thung Song Hong", "cn": "通颂洪 (Thung Song Hong)", "ru": "Тхунг Сонг Хонг"}', true, 714, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_lak_si', '{"th": "หลักสี่ (สายสีแดง)", "en": "Lak Si (Red Line)", "cn": "拉席 (红线) (Lak Si (Red Line))", "ru": "Лакси (Красная линия)"}', true, 716, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_don_mueang', '{"th": "ดอนเมือง (สายสีแดง)", "en": "Don Mueang (Red Line)", "cn": "廊曼 (红线) (Don Mueang (Red Line))", "ru": "Донмыанг (Красная линия)"}', true, 718, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_kan_kheha', '{"th": "การเคหะ", "en": "Kan Kheha", "cn": "甘克哈 (Kan Kheha)", "ru": "Кан Кеха"}', true, 720, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_lak_hok', '{"th": "หลักหก", "en": "Lak Hok", "cn": "拉六 (Lak Hok)", "ru": "Лак Хок"}', true, 722, '{"transit_type": "SRT_RED"}'),
('TRANSIT_STATION', 'srt_rangsit', '{"th": "รังสิต", "en": "Rangsit", "cn": "兰实 (Rangsit)", "ru": "Рангсит"}', true, 724, '{"transit_type": "SRT_RED"}'),

-- ==========================================
-- 🚌 BRT Bus Line (ครบทุกสถานี สาทร - ราชพฤกษ์)
-- ==========================================
('TRANSIT_STATION', 'brt_sathorn', '{"th": "สาทร (BRT)", "en": "Sathorn (BRT)", "cn": "沙吞 (BRT) (Sathorn (BRT))", "ru": "Саторн (BRT)"}', true, 800, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_akhan_songkhro', '{"th": "อาคารสงเคราะห์", "en": "Akhan Songkhro", "cn": "阿坎松科 (Akhan Songkhro)", "ru": "Акхан Сонгкро"}', true, 802, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_technic_krungthep', '{"th": "เทคนิคกรุงเทพ", "en": "Technic Krungthep", "cn": "曼谷技术学院 (Technic Krungthep)", "ru": "Техник Крунгтхеп"}', true, 804, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_thanon_chan', '{"th": "ถนนจันทน์", "en": "Thanon Chan", "cn": "真路 (Thanon Chan)", "ru": "Тханон Чан"}', true, 806, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_nararam_3', '{"th": "นราราม 3", "en": "Nararam 3", "cn": "娜拉然 3 (Nararam 3)", "ru": "Нарарам 3"}', true, 808, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_wat_dan', '{"th": "วัดด่าน", "en": "Wat Dan", "cn": "丹寺 (Wat Dan)", "ru": "Ват Дан"}', true, 810, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_wat_pariwat', '{"th": "วัดปริวาส", "en": "Wat Pariwat", "cn": "巴里瓦寺 (Wat Pariwat)", "ru": "Ват Париват"}', true, 812, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_wat_dokmai', '{"th": "วัดดอกไม้", "en": "Wat Dokmai", "cn": "多迈寺 (Wat Dokmai)", "ru": "Ват Докмай"}', true, 814, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_rama_ix_bridge', '{"th": "สะพานพระราม 9", "en": "Rama IX Bridge", "cn": "拉玛九桥 (Rama IX Bridge)", "ru": "Мост Рамы IX"}', true, 816, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_charoen_rat', '{"th": "เจริญราษฎร์", "en": "Charoen Rat", "cn": "乍伦拉 (Charoen Rat)", "ru": "Чароен Рат"}', true, 818, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_rama_iii_bridge', '{"th": "สะพานพระราม 3", "en": "Rama III Bridge", "cn": "拉玛三桥 (Rama III Bridge)", "ru": "Мост Рамы III"}', true, 820, '{"transit_type": "BRT"}'),
('TRANSIT_STATION', 'brt_ratchaphruek', '{"th": "ราชพฤกษ์ (BRT)", "en": "Ratchaphruek (BRT)", "cn": "拉差弗 (BRT) (Ratchaphruek (BRT))", "ru": "Ратчапхрык (BRT)"}', true, 822, '{"transit_type": "BRT"}')

ON CONFLICT (type, code) DO UPDATE SET
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active,
  metadata = COALESCE(ref_master_data.metadata, '{}'::jsonb) || EXCLUDED.metadata;