import {
  ShieldCheck,
  Tag,
  Home,
  Maximize,
  Coins,
  MapPin,
  Map,
  Train,
  BedDouble,
  Bath,
  Layers,
  Car,
  PawPrint,
  LayoutGrid,
  FileText,
  Clock,
} from "lucide-react";
import { ComparisonRow } from "./types";

export const COMPARISON_ROWS: ComparisonRow[] = [
  { key: "title", label: "หัวข้อ", icon: FileText },
  { key: "verified", label: "สถานะ", icon: ShieldCheck },
  { key: "listing_type", label: "ประเภทประกาศ", icon: Tag },
  { key: "property_type", label: "ประเภทอสังหาฯ", icon: Home },
  { key: "property_size", label: "ขนาด", icon: Maximize },
  { key: "price", label: "ราคา", icon: Coins },
  { key: "zone", label: "โซน/ย่าน", icon: MapPin },
  { key: "location", label: "ทำเลที่ตั้ง", icon: Map },
  { key: "google_maps_link", label: "แผนที่", icon: MapPin },
  { key: "transportation", label: "รถไฟฟ้า", icon: Train },
  { key: "bedrooms", label: "ห้องนอน", icon: BedDouble },
  { key: "bathrooms", label: "ห้องน้ำ", icon: Bath },
  { key: "floor", label: "ชั้น", icon: Layers },
  { key: "parking_slots", label: "ที่จอดรถ", icon: Car },
  { key: "petFriendly", label: "สัตว์เลี้ยง", icon: PawPrint },
  { key: "features", label: "สิ่งอำนวยความสะดวก", icon: LayoutGrid },
  { key: "nearby_places", label: "สถานที่ใกล้เคียง", icon: MapPin },
  { key: "province", label: "จังหวัด", icon: Map },
  { key: "description", label: "รายละเอียด", icon: FileText },
  { key: "updated_at", label: "อัปเดตล่าสุด", icon: Clock },
];
